application: kochliste-hrd
version: 2

runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: django
  version: "1.2"

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: main.py

